export const FIND_MY_LOCATION = "FIND_MY_LOCATION";
export const SET_DISTANCE = "SET_DISTANCE";
export const SET_ACTIVE_CATEGORY = "SET_ACTIVE_CATEGORY";
export const FETCH_BY_CATEGORY_REQEST = "FETCH_BY_CATEGORY_REQEST";
export const FETCH_BY_CATEGORY_SUCCESS = "FETCH_BY_CATEGORY_SUCCESS";
export const FETCH_BY_CATEGORY_ERROR = "FETCH_BY_CATEGORY_ERROR";
