export const listCategories = [
  { fullName: "accommodation.hotel", name: "Hotel" },
  { fullName: "accommodation.hut", name: "Hut" },
  { fullName: "accommodation.chalet", name: "Chalet" },
  { fullName: "accommodation.guest_house", name: "Guest house" },
  { fullName: "accommodation.hostel", name: "Hostel" },
  { fullName: "accommodation.motel", name: "Motel" },
  { fullName: "activity.community_center", name: "Community center" },
  { fullName: "activity.sport_club", name: "Sport club" },
  { fullName: "commercial.supermarket", name: "Supermarket" },
  { fullName: "commercial.marketplace", name: "Marketplace" },
  { fullName: "commercial.shopping_mall", name: "Shopping mall" },
  { fullName: "commercial.department_store", name: "Departmant store" },
  { fullName: "commercial.elektronics", name: "Electronics" },
  {
    fullName: "commercial.outdoor_and_sport.water_sports",
    name: "Water sports",
  },
  { fullName: "commercial.outdoor_and_sport.ski", name: "Ski" },
  { fullName: "commercial.outdoor_and_sport.diving", name: "Driving" },
  { fullName: "commercial.outdoor_and_sport.hunting", name: "Hunting" },
  { fullName: "commercial.outdoor_and_sport.bicycle", name: "Bicycle" },
  { fullName: "commercial.outdoor_and_sport.fishing", name: "Fishing" },
  { fullName: "commercial.outdoor_and_sport.golf", name: "Golf" },
  { fullName: "commercial.vehicle", name: "Vehicle" },
  // { fullName: , name:  },
  // { fullName: , name:  },
  // { fullName: , name:  },
  // { fullName: , name:  },
  // { fullName: , name:  },
  // { fullName: , name:  },
  // { fullName: , name:  },
  // "commercial.hobby",
  // "commercial.hobby.model",
  // "commercial.hobby.anime",
  // "commercial.hobby.collecting",
  // "commercial.hobby.games",
  // "commercial.hobby.brewing",
  // "commercial.hobby.photo",
  // "commercial.hobby.music",
  // "commercial.hobby.sewing_and_knitting",
  // "commercial.hobby.art",
  // "commercial.books",
  // "commercial.gift_and_souvenir",
  // "commercial.stationery",
  // "commercial.newsagent",
  // "commercial.tickets_and_lottery",
  // "commercial.clothing",
  // "commercial.clothing.shoes",
  // "commercial.clothing.clothes",
  // "commercial.clothing.underwear",
  // "commercial.clothing.sport",
  // "commercial.clothing.men",
  // "commercial.clothing.women",
  // "commercial.clothing.kids",
  // "commercial.clothing.accessories",
  // "commercial.bag",
  // "commercial.baby_goods",
  // "commercial.agrarian",
  // "commercial.garden",
  // "commercial.houseware_and_hardware",
  // "commercial.houseware_and_hardware.doityourself",
  // "commercial.houseware_and_hardware.hardware_and_tools",
  // "commercial.houseware_and_hardware.building_materials",
  // "commercial.houseware_and_hardware.building_materials.paint",
  // "commercial.houseware_and_hardware.building_materials.glaziery",
  // "commercial.houseware_and_hardware.building_materials.doors",
  // "commercial.houseware_and_hardware.building_materials.tiles",
  // "commercial.houseware_and_hardware.building_materials.windows",
  // "commercial.houseware_and_hardware.building_materials.flooring",
  // "commercial.houseware_and_hardware.fireplace",
  // "commercial.houseware_and_hardware.swimming_pool",
  // "commercial.florist",
  // "commercial.furniture_and_interior",
  // "commercial.furniture_and_interior.lighting",
  // "commercial.furniture_and_interior.curtain",
  // "commercial.furniture_and_interior.carpet",
  // "commercial.furniture_and_interior.kitchen",
  // "commercial.furniture_and_interior.bed",
  // "commercial.furniture_and_interior.bathroom",
  // "commercial.chemist",
  // "commercial.health_and_beauty",
  // "commercial.health_and_beauty.pharmacy",
  // "commercial.health_and_beauty.optician",
  // "commercial.health_and_beauty.medical_supply",
  // "commercial.health_and_beauty.hearing_aids",
  // "commercial.health_and_beauty.herbalist",
  // "commercial.health_and_beauty.cosmetics",
  // "commercial.health_and_beauty.wigs",
  // "commercial.toy_and_game",
  // "commercial.pet",
  // "commercial.food_and_drink",
  // "commercial.food_and_drink.bakery",
  // "commercial.food_and_drink.deli",
  // "commercial.food_and_drink.frozen_food",
  // "commercial.food_and_drink.pasta",
  // "commercial.food_and_drink.spices",
  // "commercial.food_and_drink.organic",
  // "commercial.food_and_drink.honey",
  // "commercial.food_and_drink.rice",
  // "commercial.food_and_drink.nuts",
  // "commercial.food_and_drink.health_food",
  // "commercial.food_and_drink.ice_cream",
  // "commercial.food_and_drink.seafood",
  // "commercial.food_and_drink.fruit_and_vegetable",
  // "commercial.food_and_drink.farm",
  // "commercial.food_and_drink.confectionery",
  // "commercial.food_and_drink.chocolate",
  // "commercial.food_and_drink.butcher",
  // "commercial.food_and_drink.cheese_and_dairy",
  // "commercial.food_and_drink.drinks",
  // "commercial.food_and_drink.coffee_and_tea",
  // "commercial.convenience",
  // "commercial.discount_store",
  // "commercial.smoking",
  // "commercial.second_hand",
  // "commercial.gas",
  // "commercial.weapons",
  // "commercial.pyrotechnics",
  // "commercial.energy",
  // "commercial.wedding",
  // "commercial.jewelry",
  // "commercial.watches",
  // "commercial.art",
  // "commercial.antiques",
  // "commercial.video_and_music",
  // "commercial.erotic",
  // "commercial.trade",
  // "commercial.kiosk",
  // "catering",
  // "catering.restaurant",
  // "catering.fast_food",
  // "catering.food_court",
  // "catering.bar",
  // "catering.pub",
  // "catering.ice_cream",
  // "catering.cafe",
  // "catering.biergarten",
  // "education ",
  // "education.school",
  // "education.driving_school",
  // "education.music_school",
  // "education.language_school",
  // "education.library",
  // "education.college",
  // "education.university",
  // "childcare",
  // "childcare.kindergarten",
  // "entertainment",
  // "entertainment.culture",
  // "entertainment.culture.theatre",
  // "entertainment.culture.arts_centre",
  // "entertainment.culture.gallery",
  // "entertainment.zoo",
  // "entertainment.aquarium",
  // "entertainment.planetarium",
  // "entertainment.museum",
  // "entertainment.cinema",
  // "entertainment.amusement_arcade",
  // "entertainment.escape_game",
  // "entertainment.miniature_golf",
  // "entertainment.bowling_alley",
  // "entertainment.flying_fox",
  // "entertainment.theme_park",
  // "entertainment.water_park",
  // "healthcare",
  // "healthcare.clinic_or_praxis",
  // "healthcare.clinic_or_praxis.allergology",
  // "healthcare.clinic_or_praxis.vascular_surgery",
  // "healthcare.clinic_or_praxis.urology",
  // "healthcare.clinic_or_praxis.trauma",
  // "healthcare.clinic_or_praxis.rheumatology",
  // "healthcare.clinic_or_praxis.radiology",
  // "healthcare.clinic_or_praxis.pulmonology",
  // "healthcare.clinic_or_praxis.psychiatry",
  // "healthcare.clinic_or_praxis.paediatrics",
  // "healthcare.clinic_or_praxis.otolaryngology",
  // "healthcare.clinic_or_praxis.orthopaedics",
  // "healthcare.clinic_or_praxis.ophthalmology",
  // "healthcare.clinic_or_praxis.occupational",
  // "healthcare.clinic_or_praxis.gynaecology",
  // "healthcare.clinic_or_praxis.general",
  // "healthcare.clinic_or_praxis.gastroenterology",
  // "healthcare.clinic_or_praxis.endocrinology",
  // "healthcare.clinic_or_praxis.dermatology",
  // "healthcare.clinic_or_praxis.cardiology",
  // "healthcare.dentist",
  // "healthcare.dentist.orthodontics",
  // "healthcare.hospital",
  // "healthcare.pharmacy",
  // "heritage",
  // "heritage.unesco",
  // "leisure",
  // "eisure.picnic",
  // "leisure.picnic.picnic_site",
  // "leisure.picnic.picnic_table",
  // "leisure.picnic.bbq",
  // "leisure.playground",
  // "leisure.spa",
  // "leisure.spa.public_bath",
  // "leisure.spa.sauna",
  // "leisure.park",
  // "leisure.park.garden",
  // "leisure.park.nature_reserve",
  // // "slovo n",
  // "natural",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
  // "",
];
